---
- name: Install and start tuned
  hosts: all
  become: yes
  tasks:
    - name: Install tuned package
      ansible.builtin.package:
        name: tuned
        state: present

    - name: Start tuned service
      ansible.builtin.service:
        name: tuned
        state: started
        enabled: yes
