---
- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present
  notify: Restart Apache

- name: Create index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Open port 80
  ansible.builtin.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Check Apache is running
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
